log_dir: "checkpoints"
save_freq: 1 # 10
device: "cuda"
epochs: 500
batch_size: 64 # 256
pretrained_model: ""
train_data: "data/train.processed.csv"
val_data: "data/val.processed.csv"
show_progress: false

dataset_params:
  max_text_len: 256

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 81
   token_embedding_dim: 256

optimizer_params:
  lr: 0.0005
